$(document).ready(function() 
{
	$(".pt-trigger").click(function()
	{
	 if(($(this).attr("data-goto"))==-1)
	 {
	   $(".logo").hide('slide',300);
	   $(".nav-btn").css("color","#f8f6f5");
	   $('.project-visual').addClass('active');
	 }
	 else
	 {
	   $(".logo").show('slide',300);
	   $(".nav-btn").css("color","#262427");
	   $('.project-visual').removeClass('active');
	 }
	});
});		