$(document).ready(function() 
{
	$(".pt-trigger").click(function()
	{
	 if(($(this).attr("data-goto"))==-1)
	 {
	   $(".logo").hide('slide',500,'ease-in-out');
	   $(".nav-btn").css("color","#f8f6f5");
	   $('.project-visual').addClass('active');
	 }
	 else
	 {
	 	$('.project-visual').removeClass('active');
	 	$(".nav-btn").css("color","#262427");
	  $(".logo").show('slide',500,'ease-in-out'); 
	 }
	});
});		